// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpgjajeawmfdusnwkqck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwZ2phamVhd21mZHVzbndrcWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODIzNjcsImV4cCI6MjA1ODA1ODM2N30.4JFT-J33PADmt5n5q-_XwWu-VhUg0Fp4946duARcWlE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);